version: "3.7"
services:
  api:
    image: api:v1
    container_name: api
    restart: always
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      TESTING: 0
    env_file:
      - ./backend/.env.api
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    env_file:
      - ./backend/.env.db
    volumes:
      - postgres_data:/var/lib/postgesql/data
      
  db_test:
    image: postgres:16
    container_name: db_test
    env_file:
      - ./backend/.env.db
      
volumes:
  postgres_data:
